### ISSUE TITLE
MapboxSearch (< 2.0, >= 1.0.0-beta) not install

### ISSUE THREAD

**Issue by PragneshVitthani** [mapbox/search-ios-examples#3]
get Specs satisfying the `MapboxSearch (< 2.0, >= 1.0.0-beta)` dependency were found, but they required a higher minimum deployment target. error when install pod.

**Comment by OdNairy** [comment]
Hi, @PragneshVitthani 
What is the actual deployment target in your project? MapboxSearchSDK requires iOS 11+

**Comment by tzevoon** [comment]
This one seems to work for me

```ruby
platform :ios, '12.0'

target 'Test4_Mapbox' do
  use_frameworks!
   pod 'MapboxMaps', '10.0.0-rc.7'
   pod 'MapboxSearch', '1.0.0-beta.11'
   pod 'MapboxSearchUI', '1.0.0-beta.11'

end
```
