### ISSUE TITLE
SeachUI search for address

### ISSUE THREAD

**Issue by DiegoResnik** [mapbox/search-ios-examples#5]
Trying Mapbox SearchUI.
When searching, I've noticed suggestions and results are only when the string I'm searching for is part of a name of a place...matching street names and addresses are not returned.
The documentation is not very detailed, since default did not provided the required results I've tried to use SearchOptions, it has a property named filterTypes.
It's of SearchQueryType type, tried to set it with [.address, .place, .locality, .street] and got an error..
I've noticed 'street' value is the cause of the error, so I removed the 'street' value and it started working again with no errors, but with no street/address results only names of places.
Also tried with and without languages option..
What am I missing?

```
        var options = SearchOptions()
        
        options.languages = ["en","he"]
        
       // options.fuzzyMatch = true
        //country, region, postcode, district, place, locality, neighborhood, address, poi, street.
        options.filterTypes = [.address, .place, .locality]
        options.origin = mapView.userLocation.coordinate

```
```
pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-beta.20'

pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-beta.20'```
```

**Comment by OdNairy** [comment]
Hey, @DiegoResnik 
Thanks for the feedback. Mapbox Search API matches results for all available metadata. For technical reasons, SearchUI may not highlight the matching part if it was not displayed. 

> default did not provided the required results

Can you say a bit more – what was wrong with default options for your case? By default, SDK doesn't filter suggestions and results by type.

> It's of SearchQueryType type, tried to set it with [.address, .place, .locality, .street] and got an error..

What type of error did you get? Can you share a bit more code, especially I'm interested in how you create MapboxSearchController and how you update SearchOptions.

**Comment by DiegoResnik** [comment]
Hi @OdNairy. 

Thank you for your prompt answer. I will try to explain better.
I'm testing the SearchUI, searching for a simple street name.
Without setting **any** search options, I tried to search a few street names both in English and Hebrew - the results included only places with names that contain the name of the street and not the street itself (see attachments 1-6.png).

![1](https://user-images.githubusercontent.com/19625881/130099852-0d69b04a-55a6-4ada-a750-99b8706bf052.PNG)
![2](https://user-images.githubusercontent.com/19625881/130099860-6296ba6a-4a05-456a-a819-a0027ac8ed21.PNG)
![3](https://user-images.githubusercontent.com/19625881/130099864-81812f41-5fd3-4b11-94ee-f9bd4e8215be.PNG)
![4](https://user-images.githubusercontent.com/19625881/130099866-b63e7bba-e607-4896-9b91-392fa4b3a1f4.PNG)
![5](https://user-images.githubusercontent.com/19625881/130099869-f9a5cc2a-333e-408e-a284-e917e3b9a35a.PNG)
![6](https://user-images.githubusercontent.com/19625881/130099872-cc07ae7d-a21b-4032-abf8-7fecde49f16b.PNG)


Since this didn't work I tried to add some hints including the country (also to avoid getting results from 10000km away?!) , hint for search in English or Hebrew
 and filtertypes, see this method that includes all:

```
private func initSearchOptions()
    {
        var options = SearchOptions()
        
        let SearchRange = UserDefaults.standard.string(forKey: "SearchRange")
        
        if (SearchRange == "currentCountry")
        {
            //limit search for the current country
            if let countryCode = (Locale.current as NSLocale).object(forKey: .countryCode) as? String {
                options.countries = [countryCode]
            }
        }
        
        options.languages = ["en","he"]
        
       // options.fuzzyMatch = true
        //country, region, postcode, district, place, locality, neighborhood, address, and poi.
        options.filterTypes = [.address, .place, .locality, .street]
        options.origin = mapView.userLocation.coordinate
        
        searchController.searchEngine.defaultSearchOptions = options
        searchController.searchOptions = options
    }
```
When the filterTypes array contains ".street" I get an error, see following attachment (attachment 7.png).

![7](https://user-images.githubusercontent.com/19625881/130099841-ebb34f15-219e-4ff4-8322-8cc941a041bc.PNG)

In the last image you can see that the street name I was looking for, exists in the map..So I'm guessing this is not a mapping issue (attachment 8.png).

![8](https://user-images.githubusercontent.com/19625881/130099847-1ea0d9c5-f7a0-4d50-9de3-ea9c6d1a71f4.PNG)

As for MapboxSearchController you asked:

```
    let searchController = MapboxSearchController(accessToken: RemoteConfigManager.mapboxToken)
    
    override func viewDidLoad() {
        super.viewDidLoad()

        let panelController = MapboxPanelController(rootViewController: searchController)
        searchController.delegate = self
        addChild(panelController)
        
        initSearchOptions()
               
    }
```

I hope it is clearer now,  I'm guessing I'm missing something...I hope you can help me out.

Tell me if you need more information.

Thank you in advance.

**Comment by OdNairy** [comment]
@DiegoResnik 
Thanks for your feedback. It looks like that `.street` filter option is unsupported for the latest public API version. Please, ignore this option until public SDK release. However, `.address` filter type includes `.street` behaviour in general. 
You implemented SearchEngine properly but, unfortunately, we have limited search coverage in Israel at the moment and that's the real reason why you don't see any valid search results.

**Comment by DiegoResnik** [comment]
Hi @OdNairy ,
Thanks again for your answer.
So although the streets I looked for appear on your navigation map, they're missing in the geocoding API ? 
If I'll provide latitude and longitude instead of an address, will the directions API know to build a route/s?

**Comment by OdNairy** [comment]
Engineers say that you can use that example as a template - https://github.com/mapbox/mapbox-navigation-ios#configuration

```swift
// Define two waypoints to travel between
let origin = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 38.9131752, longitude: -77.0324047), name: "Mapbox")
let destination = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 38.8977, longitude: -77.0365), name: "White House")

// Set options
let routeOptions = NavigationRouteOptions(waypoints: [origin, destination])

// Request a route using MapboxDirections
Directions.shared.calculate(routeOptions) { [weak self] (session, result) in
    switch result {
    case .failure(let error):
        print(error.localizedDescription)
    case .success(let response):
        guard let strongSelf = self else {
            return
        }
        // Pass the generated route response to the the NavigationViewController
        let viewController = NavigationViewController(for: response, routeIndex: 0, routeOptions: routeOptions)
        viewController.modalPresentationStyle = .fullScreen
        strongSelf.present(viewController, animated: true, completion: nil)
    }
}
```

**Comment by DiegoResnik** [comment]
@OdNairy , I'll try that ! thank you!!
