### ISSUE TITLE
Search SDK Crashing on iOS 15

### ISSUE THREAD

**Issue by weifageo** [mapbox/search-ios-examples#6]
Hello Mapbox Team,

We recently had some feedback from a customer using an iPhone 12 Pro Max,  saying our App crashes when they use the search.  They were trying to type in “Chilliwack” and it would completely crash the app after typing in just the “C”.  I've asked our developer to look into the issue and he found the following Exception occurring.

*** Assertion failure in -[MapboxSearchUI.SearchSuggestionCell _setHostsLayoutEngine:]
, NSLayoutConstraint_UIKitAdditions.m:3806

 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Must translate autoresizing mask into constraints to have _setHostsLayoutEngine:YES.'
***

Seems to be affecting iOS 15 only.

Wasn't sure if you are aware of this issue or know of a potential solution, but I wanted to forward it on to your team just in case.

Thanks for your support!

**Comment by don1ck** [comment]
Hello @weifageo!

This issue was recently fixed.
Please consider updating search sdk to latest beta version. 

Let me know if it helps, thanks :)

**Comment by OdNairy** [comment]
Thanks for report.
That known issue was fixed in `1.0.0-beta.13` version.

**Comment by weifageo** [comment]
Thanks for getting back to me so quickly!

As per the suggestion, my dev tried to update SDK 1.0.0-beta.13 version but Terminal gives him this:

[!] CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In snapshot (Podfile.lock):
    MapboxMobileEvents (= 0.10.2, ~> 0.10.0)

  In Podfile:
    MapboxSearchUI (< 2.0, >= 1.0.0-beta.13) was resolved to 1.0.0-beta.13, which depends on
      MapboxSearch (< 2.0, >= 1.0.0-beta.13) was resolved to 1.0.0-beta.13, which depends on
        MapboxMobileEvents (~> 1.0.3)

Specs satisfying the `MapboxMobileEvents (= 0.10.2, > 0.10.0), MapboxMobileEvents (> 1.0.3)` dependency were found, but they required a higher minimum deployment target.

In podfile he has set "11.0" minimum deployment target.  Also tried 15.0 but not working.

Any ideas how we can resolve this error?

**Comment by OdNairy** [comment]
@weifageo Can you change your `Podfile` to look following:

```ruby
pod 'MapboxSearchUI', ">= 1.0.0-beta.1", "< 2.0"
```

and run `pod update`? 
It successfully updates my sample project to the 1.0.0-beta.15 (including MapboxCommon 20.0.0) with deployment target `11.0`

Full sample Podfile:

```ruby
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'SearchUI-CocoaPodsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MapboxSearchUI', ">= 1.0.0-beta.1", "< 2.0"

end

```

**Comment by weifageo** [comment]
Excellent that resolved our dependency issues, the app no longer crashes upon Search!!

Thanks again for your support!!!
